# Generated by Django 5.0.6 on 2024-08-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_carinvetory_cars_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinvetory',
            name='cars_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Carros em Estoque'),
        ),
    ]
