# Generated by Django 5.0.6 on 2024-08-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_carinvetory_cars_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinvetory',
            name='cars_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Total em do Estoque'),
        ),
    ]
