# Generated by Django 5.0.6 on 2024-08-21 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_km'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
    ]
